### ISSUE TITLE
data

### ISSUE THREAD

**Issue by shainaraza** [michadenheijer/pynytimes#1]
the data is not being scrapped for articles search method, anything you tell to correct?

**Comment by michadenheijer** [comment]
Hmmmmm, the article search method isn't really great yet, but it should work. Could you explain your problem?

**Comment by shainaraza** [comment]
unable to retrieve, is it something not up from API side?

**Comment by michadenheijer** [comment]
Could you post your error? It could be that you're using an invalid API key, but I can't be sure without the error.

**Comment by Randy-whiteSugar** [comment]
Sorry to say that I met the same problem,  it says that:
File "D:\python_anaconda\lib\site-packages\pynytimes\api.py", line 174, in article_search
    result += res.json().get("response").get("docs")
AttributeError: 'NoneType' object has no attribute 'get'
I am wonder if the api returns empty result again.
I tried to write my own spider with the api and my spider get empty results after just about 20 pages.
Eager to get the news data, so please help me!

**Comment by michadenheijer** [comment]
This issue should be resolved in version 0.3 (you can update using pip).
