### ISSUE TITLE
Invalid string format

### ISSUE THREAD

**Issue by abdulsamet** [michadenheijer/pynytimes#41]
https://github.com/michadenheijer/pynytimes/blob/58539efc68a5941ffadb830536d99de16f8ea5a5/pynytimes/api.py#L467

**Comment by michadenheijer** [comment]
Could you maybe explain what the error is? When I run this function it works.

**Comment by SkyBlu132** [comment]
Hi Micha - I'm getting a similar issue with the 'Archive Metadata.' I was testing it on my Windows computer and when I use the API, it uses date.strftime("%Y/%-m").

On windows it only works with date.strftime("%Y/%#m"). I think it has to do with formatting.

I'm currently an undergrad student using your API which is great! I have limited experience but I'm hoping there's a workaround this issue so I can use it as part of my project :)

**Comment by michadenheijer** [comment]
Ah that makes sense. I checked on my Mac and sadly `.strftime("%Y/%#m")` does not work. But I found another solution that solves the problem without checking the OS.

I don't have a Windows computer, but I'm pretty sure that pull requests #47 solves the problem. If you update to version 0.6.0 then it should be resolved.
