### ISSUE TITLE
[BUG] Link to the Nyt Developers portal is incorrect

### ISSUE THREAD

**Issue by sergio-ns** [michadenheijer/pynytimes#74]
**Describe the bug**
Link to the Nyt developers portal is incorrect.
It's currently: [https://developer.nytimes.com](https://developer.nytimes.com)
It should be: [https://developers.nytimes.com](https://developers.nytimes.com)

**Comment by michadenheijer** [comment]
Are you sure? When I visit https://developer.nytimes.com it works just fine.
