### ISSUE TITLE
[QUESTION] Can articles saved in a user account's profile be accessed via this API

### ISSUE THREAD

**Issue by sergio-ns** [michadenheijer/pynytimes#75]
I'd like to retrieve the list of articles saved on my NYT user account but I could not find a way to do it via this API.

Is there a way to do it?

Thanks

**Comment by michadenheijer** [comment]
I believe there's no endpoint using the NYT developer API to get that data. However you might be able to reverse engineer such an endpoint using the app. I haven't looked into it though.
